### PR TITLE
Issue 113

### PR DESCRIPTION
**Pull request by mcupak**
This is a rebased version of #115 submitted from a branch in the main repo for collaboration. Some fixes for the build have been added on top of #115.

### CODE REVIEW

**Comment by mcupak** [comment]
TODO: Fix the versions of ga4gh-consent-codes and ADA-M dependencies.

**Comment by antbro** [comment]
What does “Fix” mean?
Tony

**Comment by mcupak** [comment]
Sorry about the ambiguity. It means to refer to a fixed, stable tag (to be created) instead of a moving branch. Otherwise we risk our spec gets broken as a result of a change in its dependencies.

**Comment by sdelatorrep** [comment]
Hi @mcupak . Do you think this PR can be merged and closed? Or maybe just closed without merging as it's outdated.

**Comment by mcupak** [comment]
This is now out of date. Closing.

**Pull request closed without merging**
