### PR TITLE
Structural variants: mateName for fusions

### PR DESCRIPTION
**Pull request by mbaudis**
This PR:

* adds a `mateName` attribute to `BeaconAlleleRequest`, to allow for the query of fusion events using the "BND" `variantType`
*  extends the inline documentation for variantType for the "BND" instance
* changes some of the multiline documentation style from YAML "Folded style" to "Literal Style" 

The naming of the attribute as `mateName` is open for changes. Some further documentation is probably needed (e.g. if `mateName` defined, it is always to be associated with the `end` | `endMin` + `endMax` values ...<sup>*</sup>).

<sup>*</sup>One may argue that the `end` position always has an associated chromosome, which is equal to `referenceName` if no `mateName` is specified

### CODE REVIEW

**Comment by garysaunders** [comment]
@juhtornr is there a downside to including this in the 1.0.0 release?

If doing so would require additional work then I agree that we should postpone to v1.0.1.

**Comment by sdelatorrep** [comment]
I think this should be part of next version (v0.5, v1.01 or whatever).

**Comment by mbaudis** [comment]
I agree with @sdelatorrep. This is a necessary but far reaching addition; e.g. one then needs examples for the reference implementation and preferably a real demonstrator dataset.

So the `mateName` is post "GA4GH v1"; but nevertheless should now be picked up ASAP for all necessary implementations.

(The BND documentation would be finr right now but not strictly necessary; better to stick with Sabela's original suggestion to keep the issues as one.)

**Comment by garysaunders** [comment]
OK let's postpone to v1.0.1.

**Comment by mcupak** [comment]
Interesting feature. It's new functionality though, so it shouldn't go into a patch release (e.g. 1.0.1). It should go into a minor release (e.g. 1.1).

Can you link the commits to an issue please?

**Comment by mcupak** [comment]
Also needs rebasing now!

**Comment by mbaudis** [comment]
@sdelatorrep @jrambla This should be merged/cleaned by somebody else (not myself ...). AFAIK the best woukld be:

* new clean PR against current dev branch
* small fixes (e.g. the chromosome note should be edited (removing the explicit 1-22, X, Y description).

**Comment by jrambla** [comment]
We are closing it because we have moved the content to PR #256

**Pull request closed without merging**
